name = "TimestampedPaths"
uuid = "ef946245-2123-4c5d-86bd-2dd9af640e77"
authors = ["Ashley Trowell"]
version = "0.1.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Dates = "1.11.0"
DocStringExtensions = "0.9.5"
Logging = "1.11.0"
Test = "1.11.0"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
