name = "TimestampedPaths"
uuid = "ef946245-2123-4c5d-86bd-2dd9af640e77"
authors = ["Ashley"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
julia = "1.9"
